language: crystal
dist: xenial

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: twitter-crystal
  local_dir: docs
  on:
    branch: master
