language: crystal
dist: xenial

crystal:
  - latest
  - nightly

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
  - crystal docs

jobs:
  allow_failures:
  - crystal: nightly

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: twitter-crystal
  local_dir: docs
  on:
    branch: master
